# Generated by Django 4.2.10 on 2024-02-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_is_lab_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_lab_user",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
