# Generated by Django 4.2.10 on 2024-02-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_address_alter_user_is_lab_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.JSONField(default=dict),
        ),
    ]
