# Generated by Django 4.2.10 on 2024-02-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0003_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
        migrations.AddField(
            model_name="order",
            name="completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
