# Generated by Django 4.2.10 on 2024-02-16 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("labs", "0004_order_attachment_order_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="lab_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
