# Generated by Django 4.2.10 on 2024-02-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0005_order_lab_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Add Attachment to complete the Order",
                null=True,
                upload_to="attachments/",
            ),
        ),
    ]
